{% set name = "azure-mgmt-resource-deploymentstacks" %}
{% set version = "1.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: 808dcdd71737e9ca4e7cb84bc62a74efd5457b6a6db0e5607cd36c86fd582dc7

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  host:
    - python
    - setuptools >=77.0.3
    - wheel
    - pip
  run:
    - python
    - isodate >=0.6.1
    - azure-mgmt-core >=1.6.0
    - typing-extensions >=4.6.0

test:
  imports:
    - azure_mgmt_resource_deploymentstacks
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Azure/azure-sdk-for-python
  summary: Microsoft Azure Deploymentstacks Management Client Library for Python
  license: MIT
  license_file: LICENSE
  license_family: MIT
  description: Microsoft Azure Deploymentstacks Management Client Library for Python
  dev_url: https://github.com/Azure/azure-sdk-for-python
  doc_url: https://github.com/Azure/azure-sdk-for-python

extra:
  recipe-maintainers:
    - and300u250w
